import { describe, it, expect } from "vitest";
import { bech32 } from "bech32";
import {
  fromPrivateKey,
  generateKleverWallet,
  assertValidSignatureHex,
} from "../src/core/wallet.js";
import { derivePublicKey, verifyFacilitatorSignature } from "../src/core/signing.js";

const TEST_PRIVATE_KEY =
  "1111111111111111111111111111111111111111111111111111111111111111";

describe("fromPrivateKey", () => {
  it("returns a KleverWallet with address, publicKeyHex, and a sign function", () => {
    const address = "klv1requester0000000000000000000000000000000";
    const w = fromPrivateKey(TEST_PRIVATE_KEY, address);
    expect(w.address).toBe(address);
    expect(w.publicKeyHex).toBe(derivePublicKey(TEST_PRIVATE_KEY));
    expect(typeof w.sign).toBe("function");
  });

  it("produces sign output that verifies against derived pubkey", () => {
    const w = fromPrivateKey(TEST_PRIVATE_KEY, "klv1x00000000000000000000000000000000000000");
    const canonicalBody = '{"a":1,"b":2}';
    const sig = w.sign(canonicalBody) as string;
    expect(sig).toMatch(/^[0-9a-f]{128}$/);
    expect(
      verifyFacilitatorSignature({
        canonicalBody,
        signatureHex: sig,
        publicKeyHex: w.publicKeyHex,
      }),
    ).toBe(true);
  });

  it("throws on missing address or private key", () => {
    expect(() => fromPrivateKey("", "klv1x00000000000000000000000000000000000000")).toThrow(
      /privateKeyHex required/,
    );
    expect(() => fromPrivateKey(TEST_PRIVATE_KEY, "")).toThrow(/address required/);
  });

  it("throws on malformed private key length", () => {
    expect(() =>
      fromPrivateKey("aa", "klv1x00000000000000000000000000000000000000"),
    ).toThrow(/32 bytes/);
  });
});

describe("generateKleverWallet (v0.3)", () => {
  it("returns { address, publicKeyHex, privateKeyHex } with expected shapes", () => {
    const w = generateKleverWallet();
    expect(w.address).toMatch(/^klv1[0-9a-z]{38,}$/);
    expect(w.publicKeyHex).toMatch(/^[0-9a-f]{64}$/);
    expect(w.privateKeyHex).toMatch(/^[0-9a-f]{64}$/);
  });

  it("generates a fresh keypair on each call (not deterministic)", () => {
    const a = generateKleverWallet();
    const b = generateKleverWallet();
    expect(a.privateKeyHex).not.toBe(b.privateKeyHex);
    expect(a.publicKeyHex).not.toBe(b.publicKeyHex);
    expect(a.address).not.toBe(b.address);
  });

  it("publicKeyHex matches derivePublicKey(privateKeyHex) — internal consistency", () => {
    const w = generateKleverWallet();
    expect(derivePublicKey(w.privateKeyHex)).toBe(w.publicKeyHex);
  });

  it("address bech32-decodes to a 32-byte payload matching the pubkey", () => {
    const w = generateKleverWallet();
    const { prefix, words } = bech32.decode(w.address);
    expect(prefix).toBe("klv");
    const bytes = new Uint8Array(bech32.fromWords(words));
    expect(bytes.length).toBe(32);
    const bytesHex = Array.from(bytes)
      .map((b) => b.toString(16).padStart(2, "0"))
      .join("");
    expect(bytesHex).toBe(w.publicKeyHex);
  });

  it("output is a valid input to fromPrivateKey (KleverWallet round-trip)", () => {
    const gen = generateKleverWallet();
    const wallet = fromPrivateKey(gen.privateKeyHex, gen.address);
    expect(wallet.address).toBe(gen.address);
    expect(wallet.publicKeyHex).toBe(gen.publicKeyHex);
    // Sign + verify round trip proves the whole chain works
    const canonicalBody = '{"hello":"world"}';
    const sig = wallet.sign(canonicalBody) as string;
    assertValidSignatureHex(sig);
    expect(
      verifyFacilitatorSignature({
        canonicalBody,
        signatureHex: sig,
        publicKeyHex: wallet.publicKeyHex,
      }),
    ).toBe(true);
  });

  it("address is exactly 62 chars (matches Klever wallet-login schema)", () => {
    // WalletLoginSchema in the Klyx backend enforces 62-char exact
    // length on klv1 addresses. A wallet generated by this helper
    // must satisfy that constraint or wallet-login rejects it.
    for (let i = 0; i < 5; i++) {
      const w = generateKleverWallet();
      expect(w.address).toHaveLength(62);
    }
  });
});
