/**
 * Real-KLV round-trip x402 settlement — end-to-end on Klever testnet.
 * ────────────────────────────────────────────────────────────────────
 *
 * Proves the full flow the offline stub examples can't: real KLV
 * moves on chain, the deployed Klyx facilitator queries the chain,
 * and returns `isValid: true` for the on-chain-anchored payment.
 *
 *   1. Load a funded testnet wallet from ./.wallet.demo.json.
 *   2. Write a temp koperator PEM for it.
 *   3. Generate a throwaway "provider" address (this example doesn't
 *      run its own provider server — we just want the settlement
 *      loop; see ../express-quickstart for the provider side).
 *   4. Generate a fresh x402 nonce.
 *   5. Shell out to `koperator account send <provider> 0.5 --message <nonce>`
 *      — real testnet Transfer tx, waits for confirmation.
 *   6. Parse the returned tx hash.
 *   7. Wait ~10s for the Klever API indexer to see the tx.
 *   8. Build a klever-exact x402 payload with `transferTx: <hash>`.
 *   9. POST to `https://facilitator.klyx.space/verify` — the facilitator
 *      fetches the tx from Klever, cross-checks the payload, signs
 *      the response with its on-chain-registered ed25519 key.
 *  10. Client verifies the response signature against the pubkey set
 *      fetched from `facilitator.klyx.space/keys`.
 *  11. Assert `isValid: true` — the round-trip is closed.
 *
 * Prerequisites:
 *   - Node 20+
 *   - koperator installed at ~/klever-sdk/koperator (or set KOPERATOR env)
 *   - .wallet.demo.json copied from .wallet.demo.json.example + funded
 *     via https://faucet.testnet.klever.finance/ (~5 KLV is plenty)
 *
 * Cost per run: 0.5 KLV transferred + a few hundred smallest-units in
 * network fees. Testnet KLV; no real economic value.
 */

import { readFileSync, writeFileSync, chmodSync, unlinkSync, existsSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { homedir } from 'node:os';
import { fileURLToPath } from 'node:url';
import { resolve, dirname } from 'node:path';
import { Buffer } from 'node:buffer';

import {
  FacilitatorClient,
  buildAndSignKleverExactPayload,
  fromPrivateKey,
  generateKleverWallet,
  NETWORK_KLEVER_TESTNET,
  SCHEME_EXACT,
  X402_VERSION,
} from '@klyx/x402';

// ── Config ─────────────────────────────────────────────────
const __dirname = dirname(fileURLToPath(import.meta.url));
const FAC_URL = 'https://facilitator.klyx.space';
const NODE_URL = 'https://node.testnet.klever.org';       // for tx broadcast
const KOPERATOR = process.env.KOPERATOR ?? resolve(homedir(), 'klever-sdk/koperator');
const WALLET_FILE = resolve(__dirname, '.wallet.demo.json');
const PEM_PATH = resolve(__dirname, '.tmp.pem');
const AMOUNT_SMALLEST = '500000';                          // 0.5 KLV in smallest units (payload)
const AMOUNT_DECIMAL_KLV = '0.5';                          // koperator takes decimal KLV

// ── Load or generate wallet ────────────────────────────────
// First-run UX: auto-generate a fresh testnet keypair so the user
// doesn't have to run a separate `node -e` incantation + hand-edit
// a JSON file. Auto-generated wallet still needs faucet funding
// (no way around that) — we exit cleanly with a big-banner "next
// step" message so the user knows exactly what to do.
if (!existsSync(WALLET_FILE)) {
  const fresh = generateKleverWallet();
  const walletData = {
    _comment:
      'TESTNET-ONLY. Auto-generated by settle.mjs on first run. DO NOT COMMIT. DO NOT reuse for mainnet.',
    ...fresh,
    network: 'klever-testnet',
    purpose: 'requester wallet for the real-KLV x402 round-trip example',
    generatedAt: new Date().toISOString(),
  };
  writeFileSync(WALLET_FILE, JSON.stringify(walletData, null, 2) + '\n');
  chmodSync(WALLET_FILE, 0o600);
  console.log(`\n✨ Generated a fresh testnet keypair at ${WALLET_FILE}`);
  console.log(`   Address: ${fresh.address}\n`);
  console.log(`   NEXT STEP — fund this address with testnet KLV, then re-run \`npm start\`.`);
  console.log(`   Faucet:  https://faucet.testnet.klever.finance/`);
  console.log(`   (~5 KLV is plenty for many runs; each run spends 0.5 KLV + tiny fee)\n`);
  process.exit(0);
}

const wallet = JSON.parse(readFileSync(WALLET_FILE, 'utf-8'));
console.log(`[1] Loaded wallet: ${wallet.address}`);

// ── Write temp koperator PEM ───────────────────────────────
// Klever PEM format: base64 of ASCII hex (privKey || pubKey), wrapped.
const pemBody = Buffer.from(wallet.privateKeyHex + wallet.publicKeyHex, 'utf-8')
  .toString('base64')
  .match(/.{1,64}/g)
  .join('\n');
writeFileSync(
  PEM_PATH,
  `-----BEGIN PRIVATE KEY for ${wallet.address}-----\n${pemBody}\n-----END PRIVATE KEY for ${wallet.address}-----\n`,
);
chmodSync(PEM_PATH, 0o600);

// ── Fresh provider + nonce ─────────────────────────────────
const provider = generateKleverWallet();
// Nonce must be lowercase hex, 32+ chars. Timestamp-based so repeat
// runs don't trip the facilitator's nonce_reused check.
const nonce =
  'aaaaaaaaaaaaaaaaaaaa' + Date.now().toString(16).padStart(12, '0');
console.log(`[2] Provider (throwaway): ${provider.address}`);
console.log(`[3] Nonce: ${nonce}`);

// ── Real KLV Transfer via koperator ────────────────────────
console.log(`\n[4] Broadcasting real Transfer via koperator...`);
console.log(`    ${KOPERATOR} account send ${provider.address} ${AMOUNT_DECIMAL_KLV}`);
console.log(`      --message ${nonce} --node ${NODE_URL} --await --sign`);

const result = spawnSync(
  KOPERATOR,
  [
    'account', 'send',
    provider.address,
    AMOUNT_DECIMAL_KLV,
    '--message', nonce,
    '--key-file', PEM_PATH,
    '--node', NODE_URL,
    '--await',
    '--sign',
  ],
  { encoding: 'utf-8', stdio: ['ignore', 'pipe', 'pipe'] },
);
try { unlinkSync(PEM_PATH); } catch {}

const combined = (result.stdout ?? '') + '\n' + (result.stderr ?? '');
if (result.status !== 0) {
  console.error(`[!] koperator exited ${result.status}`);
  console.error(combined);
  process.exit(1);
}
const hashMatch =
  combined.match(/txHash\s*=\s*([0-9a-fA-F]{40,})/i) ??
  combined.match(/"hash"\s*:\s*"([0-9a-fA-F]{40,})"/i);
if (!hashMatch) {
  console.error('[!] Could not find tx hash in koperator output. Full output:');
  console.error(combined);
  process.exit(1);
}
const txHash = hashMatch[1].toLowerCase();
console.log(`\n[5] Transfer confirmed. txHash = ${txHash}`);
console.log(`    explorer: https://testnet.kleverscan.org/transaction/${txHash}`);

// ── Wait for the Klever API indexer ────────────────────────
console.log(`\n[6] Waiting 10s for the Klever API indexer to see the tx...`);
await new Promise((r) => setTimeout(r, 10_000));

// ── Fetch trusted facilitator pubkeys ──────────────────────
// Rotation-safe — hit the facilitator's self-describing /keys
// endpoint so we're never verifying against a stale hardcoded pubkey.
const { keys: FAC_PUBKEYS } = await fetch(`${FAC_URL}/keys`).then((r) => r.json());
console.log(`[7] Trusted facilitator pubkey set: ${FAC_PUBKEYS.length} key(s)`);

// ── Build klever-exact payload with transferTx ─────────────
const signerWallet = fromPrivateKey(wallet.privateKeyHex, wallet.address);
const paymentPayload = await buildAndSignKleverExactPayload(
  {
    asset: 'KLV',
    amount: AMOUNT_SMALLEST,
    destination: provider.address,
    nonce,
    expiresAt: '2030-01-01T00:00:00Z',
    transferTx: txHash,
    wallet: signerWallet,
  },
  NETWORK_KLEVER_TESTNET,
);

const paymentRequirements = {
  scheme: SCHEME_EXACT,
  network: NETWORK_KLEVER_TESTNET,
  maxAmountRequired: AMOUNT_SMALLEST,
  resource: '/real-klv-roundtrip',
  payTo: provider.address,
  asset: 'KLV',
};

// ── POST /verify — the real facilitator, on real testnet ──
console.log(`\n[8] POST ${FAC_URL}/verify (with transferTx fast-path)`);
const facilitator = new FacilitatorClient({
  url: FAC_URL,
  publicKeysHex: FAC_PUBKEYS,
});

try {
  const verifyResult = await facilitator.verify({
    x402Version: X402_VERSION,
    paymentPayload,
    paymentRequirements,
  });
  console.log('\n--- /verify response ---');
  console.log(JSON.stringify(verifyResult.body, null, 2));

  if (verifyResult.body.isValid) {
    console.log(`\n✅ REAL KLV ROUND-TRIP PASS`);
    console.log(`   Real 0.5 KLV moved on testnet + verified by facilitator.klyx.space.`);
    console.log(`   payer confirmed: ${verifyResult.body.payer}`);
  } else {
    console.log(`\n❌ /verify returned isValid: false`);
    console.log(`   invalidReason: ${verifyResult.body.invalidReason}`);
    console.log(`   Common causes: tx not yet indexed (retry in 30s), nonce reused,`);
    console.log(`   amount mismatch (koperator takes DECIMAL KLV, payload takes smallest units).`);
  }
} catch (err) {
  console.error(`\n❌ facilitator.verify threw: ${err.name} ${err.message}`);
  if (err.code) console.error(`   code: ${err.code}`);
  if (err.responseBody) console.error(`   responseBody: ${err.responseBody}`);
}
